### ISSUE TITLE
Speedtest-cli: ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6477]
**Steps to reproduce**

```
[root@ns7loc5 ~]# rpm -qa speedtest-cli
speedtest-cli-2.1.2-1.ns7.noarch
```

launch speedtest-cli in the terminal 

```
[root@ns7loc5 ~]# speedtest-cli
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==2.1.2', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1985, in main
    shell()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1874, in shell
    secure=args.secure
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1090, in __init__
    self.get_config()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1173, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
```

**Expected behavior**

I expect no errors

**Actual behavior**

A new version is done to fix this issue : speedtest-cli-2.1.3

**Comment by stephdl** [comment]
QA

Upgrade from testing speedtest-cli

- test from the CLI 

`speedtest-cli --json | jq
`
- test from the UI in the firewall WAN panel

**Comment by gsanchietti** [comment]
Tested on command line and also on the UI.

It works good.

**Comment by gsanchietti** [comment]
Released in updates:
speedtest-cli-2.1.3-1.ns7.noarch.rpm
