### ISSUE TITLE
Placeholder could mislead system administrator 

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6788]
**Steps to reproduce**

- Install ns8-webserver and ns8-mariadb
- after the installation you need to set a web path for `/sftpgo` or `/phpmyadmin`
- we have a placeholder that should help the system administrator to write something

**Expected behavior**

I expect the system administrator should understand to write the web path and trigger the save button to start the service

**Actual behavior**

The system administrator could believe the service is already configured and started because he can read the placeholder, even it if gray and not black

**Components**

ns8-webserver
ns8-mariadb

**See also**

https://community.nethserver.org/t/install-wordpress-to-ns8/22431/20

----

thank abo1990

**Comment by stephdl** [comment]
QA

test case 1

- Install ns8-mariadb:1.0.6.dev.1
- go to configure the web Path inside the settings page
-  the web path must be empty with a placeholder that prevent you to think the module is configured, moreover you have a tooltips that brings you some guidance
- when you try to save the form with an empty  webpath a validator must block you 
- when you write a webpath without starting by a `/` a validator must stop you
- write a web path `/myadmin` and save you must have no errors


test case 2

- Install ns8-webserver:1.0.12.dev.1
- go to configure the web Path inside the settings page
-  the web path must be empty with a placeholder that prevent you to think the module is configured, moreover you have a tooltips that brings you some guidance
- when you try to save the form with an empty  webpath a validator must block you 
- when you write a webpath without starting by a `/` a validator must stop you
- write a web path `/myadmin` and save you must have no errors

**Comment by nrauso** [comment]
got errors trying to download dev modules:
```
~]# add-module ghcr.io/nethserver/ns8-mariadb:1.0.6.dev.1
<7>podman-pull-missing ghcr.io/nethserver/ns8-mariadb:1.0.6.dev.1
Trying to pull ghcr.io/nethserver/ns8-mariadb:1.0.6.dev.1...
Error: initializing source docker://ghcr.io/nethserver/ns8-mariadb:1.0.6.dev.1: Requesting bearer token: invalid status code from registry 403 (Forbidden)
Traceback (most recent call last):
  File "/usr/local/agent/bin/podman-pull-missing", line 35, in <module>
    subprocess.run(['podman', 'pull', image_url]).check_returncode()
  File "/usr/lib64/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['podman', 'pull', 'ghcr.io/nethserver/ns8-mariadb:1.0.6.dev.1']' returned non-zero exit status 125.
Traceback (most recent call last):
  File "/var/lib/nethserver/cluster/actions/add-module/50update", line 92, in <module>
    agent.run_helper('podman-pull-missing', image_url, progress_callback=agent.get_progress_callback(0,33)).check_returncode()
  File "/usr/lib64/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '('podman-pull-missing', 'ghcr.io/nethserver/ns8-mariadb:1.0.6.dev.1')' returned non-zero exit status 1.

~]# add-module ghcr.io/nethserver/ns8-webserver:1.0.12.dev.1
<7>podman-pull-missing ghcr.io/nethserver/ns8-webserver:1.0.12.dev.1
Trying to pull ghcr.io/nethserver/ns8-webserver:1.0.12.dev.1...
Error: initializing source docker://ghcr.io/nethserver/ns8-webserver:1.0.12.dev.1: Requesting bearer token: invalid status code from registry 403 (Forbidden)
Traceback (most recent call last):
  File "/usr/local/agent/bin/podman-pull-missing", line 35, in <module>
    subprocess.run(['podman', 'pull', image_url]).check_returncode()
  File "/usr/lib64/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['podman', 'pull', 'ghcr.io/nethserver/ns8-webserver:1.0.12.dev.1']' returned non-zero exit status 125.
Traceback (most recent call last):
  File "/var/lib/nethserver/cluster/actions/add-module/50update", line 92, in <module>
    agent.run_helper('podman-pull-missing', image_url, progress_callback=agent.get_progress_callback(0,33)).check_returncode()
  File "/usr/lib64/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '('podman-pull-missing', 'ghcr.io/nethserver/ns8-webserver:1.0.12.dev.1')' returned non-zero exit status 1.
```

Could you please take a look?

**Comment by stephdl** [comment]
```
[root@R4-pve ~]#  add-module ghcr.io/nethserver/ns8-nextcloud:latest
<7>podman-pull-missing ghcr.io/nethserver/ns8-nextcloud:latest
Trying to pull ghcr.io/nethserver/ns8-nextcloud:latest...
Error: initializing source docker://ghcr.io/nethserver/ns8-nextcloud:latest: Requesting bearer token: invalid status code from registry 403 (Forbidden)
```
we have some GH issue on `ghcr.io` :(, I am sorry mate

**Comment by nrauso** [comment]
Test case 1: **verified**

Test case 2: **verified**

Test case 3: **verified**

**Comment by stephdl** [comment]
released mariadb and webserver
