### ISSUE TITLE
missing environment variable EJABBERD_MODULE

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6828]
**Steps to reproduce**

- Install an account provider
- install a mail server and configure it to use the account provider
- install webtop and configure it to use the mail server
- change the account provider of the mail server (settings > general settings)
- an event `mail-settings-changed` is triggered

**Expected behavior**

I expect no error

**Actual behavior**

in the log of webtop we can find this 

```
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[109030]: Handler of module/mail1/event/mail-settings-changed is starting step 10configure_module
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]: Traceback (most recent call last):
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]:   File "/home/webtop2/.config/events/mail-settings-changed/10configure_module", line 16, in <module>
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]:     webtop.configure_module(event_input['module_id'], os.environ) # Ignore exit code
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]:   File "/home/webtop2/.config/pypkg/webtop.py", line 18, in configure_module
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]:     "ejabberd_module": penv['EJABBERD_MODULE'],
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]:                        ~~~~^^^^^^^^^^^^^^^^^^^
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]:   File "<frozen os>", line 679, in __getitem__
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[114090]: KeyError: 'EJABBERD_MODULE'
Jan 17 09:31:53 R1-pve.rocky9-pve.org agent@webtop2[109030]: exit status 1
```
It is an installation without ejabberd so the environment has been never set

**Components**

ns8-webtop

**Comment by stephdl** [comment]
first installation
- Install two account providers either two LDAP or LDAP and SAMBA) 
- install a mail server and configure it to use one account provider
- install webtop and configure it to use the mail server
`add-module ghcr.io/nethserver/webtop:1.0.11-testing.1`
- change the account provider of the mail server (mail panel > settings > general settings)
- check the log of webtop, the event  `mail-settings-changed` must occur without error


upgrade installation
- Install two account providers either two LDAP or LDAP and SAMBA) 
- install a mail server and configure it to use one account provider
- install webtop and configure it to use the mail server
- upgrade to `api-cli run update-module --data '{"module_url":"ghcr.io/nethserver/webtop:1.0.11-testing.1","instances":["webtop1"],"force":true}'` 
- change the account provider of the mail server (mail panel > settings > general settings)
- check the log of webtop, the event  `mail-settings-changed` must occur without error

**Comment by lucagasparini** [comment]
QA-1 (first instalation): VERIFIED :+1:
```
Jan 18 10:41:41 ns8 agent@webtop7[2613355]: Handler of module/mail1/event/mail-settings-changed is starting step 10configure_module
...
Jan 18 10:41:52 ns8 agent@webtop7[2613355]: task/module/webtop7/546fb4a1-9680-4191-9208-071de47db86e: action "configure-module" status is "completed" (0) at step 80enable_service
Jan 18 10:41:53 ns8 agent@webtop7[2613355]: Handler of module/mail1/event/mail-settings-changed exited with status "completed" (0) at step 10configure_module
```

QA-2 (upgrade installation): VERIFIED :+1:
```
Jan 18 11:02:41 ns8 agent@webtop1[2621281]: Handler of module/mail1/event/mail-settings-changed is starting step 10configure_module
...
Jan 18 11:02:51 ns8 agent@webtop1[2621281]: task/module/webtop1/ec2befa8-34d2-426d-b6d5-1ac87b3df22b: action "configure-module" status is "completed" (0) at step 80enable_service
Jan 18 11:02:51 ns8 agent@webtop1[2621281]: Handler of module/mail1/event/mail-settings-changed exited with status "completed" (0) at step 10configure_module
```

In both cases no `EJABBERD_MODULE` errors detected
