### ISSUE TITLE
NethServer 8 uninstall script does not clean up firewalld rules

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#6861]
The uninstall script to remove NS8 on a running machine seems not to correctly clean up the custom `firewalld` rules created during NS8 modules installation.

**Steps to reproduce**

- Install brand new NS8 on a clean machine;
- Install a `Samba AD` local provider and a module (let's say `Mail`);
- Remove NS8 with the dedicated script;
- Reinstall NS8 again;
- Try to reinstall local `Samba AD` and `Mail` module.

**Expected behavior**

Installation of user domain and module should work flawlessly.

**Actual behavior**

The installation generate errors because of already existing fw rules:
```
~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: cockpit dhcpv6-client mail1 samba1 ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

~]# ll /etc/firewalld/services/
total 20
-rw-r--r--. 1 root root 311 Feb 26 16:19 mail1.xml
-rw-r--r--. 1 root root  60 Feb 26 16:19 mail1.xml.old
-rw-r--r--. 1 root root  98 Feb 26 16:16 ns-wireguard.xml.old
-rw-r--r--. 1 root root 714 Feb 26 16:17 samba1.xml
-rw-r--r--. 1 root root  60 Feb 26 16:17 samba1.xml.old
```

Especially for the account provider, this scenario leads the system to abort its installation:
```
Feb 26 16:25:52 myrocky agent@node[11913]: firewall-cmd --permanent --new-service=samba1
...
Feb 26 16:25:52 myrocky firewalld[3426]: ERROR: NAME_CONFLICT: new_service(): 'samba1'
...
Feb 26 16:25:52 myrocky agent@node[11913]: Error: NAME_CONFLICT: new_service(): 'samba1'
Feb 26 16:25:52 myrocky rsyslogd[782]: imjournal: journal files changed, reloading...  [v8.2102.0-117.el9 try https://www.rsyslog.com/e/0 ]
Feb 26 16:25:52 myrocky agent@node[11913]: Traceback (most recent call last):
Feb 26 16:25:52 myrocky agent@node[11913]:   File "/var/lib/nethserver/node/actions/add-public-service/50add", line 34, in <module>
Feb 26 16:25:52 myrocky agent@node[11913]:     agent.run_helper(*fw_cmd, f'--new-service={name}').check_returncode()
Feb 26 16:25:52 myrocky agent@node[11913]:   File "/usr/lib64/python3.11/subprocess.py", line 502, in check_returncode
Feb 26 16:25:52 myrocky agent@node[11913]:     raise CalledProcessError(self.returncode, self.args, self.stdout,
Feb 26 16:25:52 myrocky agent@node[11913]: subprocess.CalledProcessError: Command '('firewall-cmd', '--permanent', '--new-service=samba1')' retu
rned non-zero exit status 26.
Feb 26 16:25:52 myrocky agent@node[11913]: task/node/1/cb17d295-7257-492f-9c0d-eb243fc03117: action "add-public-service" status is "aborted" (1)
 at step 50add
 ...
 Feb 26 16:25:57 myrocky agent@samba1[13502]: Assertion failed
Feb 26 16:25:57 myrocky agent@samba1[13502]:   File "/home/samba1/.config/actions/create-module/70firewall", line 11, in <module>
Feb 26 16:25:57 myrocky agent@samba1[13502]:     agent.assert_exp(agent.add_public_service(os.environ['MODULE_ID'], [
Feb 26 16:25:57 myrocky agent@samba1[13502]: task/module/samba1/879beeae-a0ed-46b6-ad26-81a27cf2a04c: action "create-module" status is "aborted" (2) at step 70firewall
Feb 26 16:25:57 myrocky agent@cluster[11904]: Assertion failed
Feb 26 16:25:57 myrocky agent@cluster[11904]:   File "/var/lib/nethserver/cluster/actions/add-module/50update", line 223, in <module>
Feb 26 16:25:57 myrocky agent@cluster[11904]:     agent.assert_exp(create_module_result['exit_code'] == 0) # Ensure create-module is successful
Feb 26 16:25:57 myrocky agent@cluster[11904]: task/cluster/89900d15-4b82-4af8-a1e7-3dfa965a47e0: action "add-module" status is "aborted" (2) at step 50update
Feb 26 16:25:57 myrocky agent@cluster[11904]: Internal provider installation failed!
Feb 26 16:25:57 myrocky agent@cluster[11904]:   File "/var/lib/nethserver/cluster/actions/add-internal-provider/50update", line 49, in <module>
Feb 26 16:25:57 myrocky agent@cluster[11904]:     agent.assert_exp(add_result['exit_code'] == 0, "Internal provider installation failed!")
Feb 26 16:25:57 myrocky agent@cluster[11904]: task/cluster/9e2054d0-4a29-43d8-baee-c0b70a6a05a7: action "add-internal-provider" status is "aborted" (2) at step 50update
```

**Components**

- `core:2.5.2`

**Comment by nrauso** [comment]
tested: **VERIFIED**

now unused fw services are deleted by the uninstall script
