### ISSUE TITLE
Delete user error in OpenLDAP user portal

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#6981]
If the LDAP domain name is long, the removal of another user member of Domain Admins fail in the OpenLDAP user portal.

**Steps to reproduce**

- Use openldap with NS8
- Create a long domain name (see below)
> modifying entry "cn=domain admins,ou=Groups,dc=leader,dc=nv-proxy,dc=mv,dc=nethserver,dc=ne"
- Create a user, member of the domain admins group
- in the user-portal with the administrator user, try to remove it

**Expected behavior**

I expect to remove the user without error

**Actual behavior**

An error is displayed,  it is impossible to remove the user

![Image](https://github.com/user-attachments/assets/61436d86-6f90-4222-b3ec-c7cbab609f7c)

In the app log a `Server is unwilling to perform (53) no global superior knowledge` message from LDAP appears:

```text
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685094]: deleting entry "uid=nethvoice15-adm,ou=People,dc=leader,dc=nv-proxy,dc=mv,dc=nethserver,dc=net"
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net slapd[2057]: slap_get_csn: conn=1093 op=1 generated new csn=20240724084941.845538Z#000000#001#000000 manage=1
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net slapd[2057]: slap_queue_csn: queueing 0x7f70bf63fc50 20240724084941.845538Z#000000#001#000000
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net slapd[2057]: slap_graduate_commit_csn: removing 0x7f70bf63fc50 20240724084941.845538Z#000000#001#000000
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685094]: ldap_modify: Server is unwilling to perform (53)
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685094]:         additional info: no global superior knowledge
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685094]: modifying entry "cn=domain admins,ou=Groups,dc=leader,dc=nv-proxy,dc=mv,dc=nethserver,dc=ne"
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685084]: Traceback (most recent call last):
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685084]:   File "/home/openldap1/.config/api-moduled/handlers/remove-user/post", line 17, in <module>
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685084]:     subprocess.run(removeuser_cmd, stdout=sys.stderr, check=True, text=True)
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685084]:   File "/usr/lib64/python3.11/subprocess.py", line 571, in run
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685084]:     raise CalledProcessError(retcode, process.args,
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[685084]: subprocess.CalledProcessError: Command '['podman', 'exec', 'openldap', 'remove-user', 'nethvoice15-adm']' returned non-zero exit status 53.
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[2661]: Error from /home/openldap1/.config/api-moduled/handlers/remove-user/post: exit status 1
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[2661]: Output validation error: JSON unmarshal error: unexpected end of JSON input. Input data: []
Jul 24 08:49:41 rl1.leader.nv-proxy.mv.nethserver.net api-moduled[2661]: [GIN] 2024/07/24 - 08:49:41 | 500 |  482.627656ms |      81.56.70.2 | POST     "/api/remove-user"
```

**Components**

version tested 2.2.3

**See also**

Discussion: https://mattermost.nethesis.it/nethesis/pl/65995dkrdibefbfszd3wh7bfua

Thanks @Amygos

**Comment by stephdl** [comment]
QA

test with version 2.2.4-dev.1 the bug is not more reproducible
test also alter-user, add-user, add-group, alter-group have no issue with a long domain name

**Comment by nrauso** [comment]
test case **VERIFIED**

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/openldap:2.2.4
