### ISSUE TITLE
External users and groups unavailable after restore

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#7027]
When restoring a cluster from a backup that has an external account provider configured, external users are not available after the restore. Attempting to list users and groups on the restored node results in an error:
```
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]: Traceback (most recent call last):
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]:   File "/var/lib/nethserver/cluster/actions/list-domain-groups/50list_groups", line 33, in <module>
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]:     groups = Ldapclient.factory(**domain).list_groups()
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]: TypeError: agent.ldapclient.Ldapclient.factory() argument after ** must be a mapping, not NoneType
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]: Traceback (most recent call last):
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]:   File "/var/lib/nethserver/cluster/actions/list-domain-users/50list_users", line 33, in <module>
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]:     users = Ldapclient.factory(**domain).list_users()
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]: TypeError: agent.ldapclient.Ldapclient.factory() argument after ** must be a mapping, not NoneType
Sep 17 15:00:22 myrocky.test.eu agent@cluster[7417]: task/cluster/95b0eaf8-671d-4b03-9c01-f1c8ebf28ba9: action "list-domain-groups" status is "aborted" (1) at step 50list_groups
```

**Steps to reproduce**

- Install and configure a fresh instance of NS8 with an external account provider;
- perform a backup and download the backup configuration file;
- reinstall NS8 from scratch and restore the configuration using the previously downloaded backup file;
- check the users and groups of the external account provider on the new NS8 node.

**Expected behavior**

You should see the users and groups from the external account provider.

**Actual behavior**

An error occurs, and no users or groups are displayed.

This seems to be an issue with `ldapproxy`.
Although the external account provider's data is correctly stored in `redis`, `ldapproxy` has no configuration:
```
~]# runagent python3 -magent.ldapproxy
adtest.it node/1 None
```
Restarting `ldapproxy` resolves the issue:
```
runagent -m ldapproxy1 systemctl --user restart ldapproxy
```

**Components**

- `core:2.9.3`
- `ldapproxy :1.0.2`

**Comment by stephdl** [comment]
QA

- install a NS8 with a remote account provider and set a backup configuration, download the backup configuration
- install a new core from ghcr.io/nethserver/core:2.9.4-dev.1 and do a full restoration from the backup file
- you must be able to restore and to use the account provider to list users and groups

**Comment by nrauso** [comment]
test case **VERIFIED**
