### ISSUE TITLE
NethVoice: Docker Rate Limit Error Causes "create-module" Action to Fail

### ISSUE THREAD

**Issue by Amygos** [NethServer/dev#7169]
The `create-module` action fails during the "05pullimages" step due to a rate limit error when pulling the `redis:7.0.10-alpine` image from Docker Hub. The error message indicates the rate limit has been exceeded.

Relevant logs:  
- The pull attempt results in multiple retries, eventually failing with a `CalledProcessError` in `podman-pull-missing`.  
- The overall status of the action is marked as "aborted."  

**Steps to reproduce**  

- Attempt to execute `add-module nethvoice`

**Expected behavior**  

The `create-module` action completes successfully without encountering rate limit errors.  

**Actual behavior**  

The `create-module` action fails during the "05pullimages" step. The Redis image pull triggers a Docker Hub rate limit error (`toomanyrequests`), causing multiple retries. After exhausting retries, the process aborts with a `CalledProcessError`. 

```
Nov 20 13:48:49 node.example.com agent@nethvoice1[66826]: Trying to pull docker.io/library/redis:7.0.10-alpine...
Nov 20 13:49:52 node.example.com agent@nethvoice1[66826]: time="2024-11-20T13:49:52Z" level=warning msg="Failed, retrying in 1s ... (1/3). Error: copying system image from manifest list: determining manifest MIME type for docker://redis:7.0.10-alpine: reading manifest sha256:98f4ea44e912d0941d29015a4e2448151b94411109c896b5627d94d79306eea7 in docker.io/library/redis: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
Nov 20 13:50:25 node.example.com agent@nethvoice1[66826]: time="2024-11-20T13:50:25Z" level=warning msg="Failed, retrying in 1s ... (2/3). Error: initializing source docker://redis:7.0.10-alpine: reading manifest 7.0.10-alpine in docker.io/library/redis: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
Nov 20 13:50:58 node.example.com agent@nethvoice1[66826]: time="2024-11-20T13:50:58Z" level=warning msg="Failed, retrying in 1s ... (3/3). Error: initializing source docker://redis:7.0.10-alpine: reading manifest 7.0.10-alpine in docker.io/library/redis: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]: Error: copying system image from manifest list: determining manifest MIME type for docker://redis:7.0.10-alpine: reading manifest sha256:98f4ea44e912d0941d29015a4e2448151b94411109c896b5627d94d79306eea7 in docker.io/library/redis: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]: Traceback (most recent call last):
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:   File "/usr/local/agent/bin/podman-pull-missing", line 35, in <module>
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:     subprocess.run(['podman', 'pull', image_url]).check_returncode()
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:   File "/usr/lib64/python3.11/subprocess.py", line 502, in check_returncode
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:     raise CalledProcessError(self.returncode, self.args, self.stdout,
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]: subprocess.CalledProcessError: Command '['podman', 'pull', 'docker.io/library/redis:7.0.10-alpine']' returned non-zero exit status 125.
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]: Traceback (most recent call last):
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:   File "/usr/local/agent/actions/create-module/05pullimages", line 48, in <module>
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:     agent.run_helper('podman-pull-missing', *images).check_returncode()
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:   File "/usr/lib64/python3.11/subprocess.py", line 502, in check_returncode
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]:     raise CalledProcessError(self.returncode, self.args, self.stdout,
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]: subprocess.CalledProcessError: Command '('podman-pull-missing', 'ghcr.io/nethesis/nethvoice-mariadb:1.1.0', 'ghcr.io/nethesis/nethvoice-freepbx:1.1.0', 'ghcr.io/nethesis/nethvoice-cti-server:1.1.0', 'ghcr.io/nethesis/nethvoice-cti-ui:1.1.0', 'ghcr.io/nethesis/nethvoice-tancredi:1.1.0', 'ghcr.io/nethesis/nethvoice-janus:1.1.0', 'ghcr.io/nethesis/nethvoice-phonebook:1.1.0', 'docker.io/library/redis:7.0.10-alpine', 'ghcr.io/nethesis/nethvoice-reports-ui:1.1.0', 'ghcr.io/nethesis/nethvoice-reports-api:1.1.0')' returned non-zero exit status 1.
Nov 20 13:51:45 node.example.com agent@nethvoice1[66826]: task/module/nethvoice1/824facd1-54ce-444e-b126-9f21f76df6f3: action "create-module" status is "aborted" (1) at step 05pullimages
```

**Comment by Amygos** [comment]
Solution implemented into the `ns8-core`: https://github.com/NethServer/dev/issues/7160
