### ISSUE TITLE
Mail stack (webtop): Migrate a mail stack and change the base DN

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7182]
We need to test the migration of an openldap directory.nh to another base DN set by the sysadmin

For this purpose the test the platform we need to install on NS7 and migrate the whole stack to NS8

nethserver-openldap
nethserver-mail-server
nethserver-webtop

**Comment by stephdl** [comment]
ghcr.io/nethserver/webtop:1.1.2-testing.2
ghcr.io/nethserver/mail:1.4.10-dev.2
testing version of nethserver-ns8-version : http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-ns8-migration-1.0.18-1.1.g865021d.ns7.x86_64.rpm

To test the event user-domain-changed and the migration of the base DN to another DN, you have to write to the /usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-webtop5/bind.env the version above and migrate the mail stack to a NS8

- install NS7 with an openldap account provider, mail and sogo
- create some data like users in LDAP, some emails
- install the testing version of nethserver-ns8-migration: `yum install http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-ns8-migration-1.0.18-1.1.g865021d.ns7.x86_64.rpm`
- modify the bind.env to set the version of `sogo, mail, roundcubemail`
this is an example : 
`vim /usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-sogo/bind.env`
change `MODULE_IMAGE_URL="webtop"`
to `MODULE_IMAGE_URL="ghcr.io/nethserver/webtop:1.1.2-testing.2"`

case1

- migrate the mail stack by the UI, set a bind DN like asked by the UI
- once the stack is migrated, using the remote account provider you can use webtop and mail
- once the test before is good, migrate the account provider
- at the end of the account provider migration, the event user-domain-changed is triggered and all the services (postfix service, dovecot service, webtop pod)  will restart (you can see it in journald of NS8)
- once the stack is migrated,do not reconfigure something, just test, you can 
- login to webtop with a user of the LDAP (do not reconfigure something) and send and receive email from webtop to a user of the ldap

**Comment by gsanchietti** [comment]
Not verified.

When the migration is finished, WebTop fails with the following error:
```
Nov 27 13:19:03 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]: Traceback (most recent call last):
Nov 27 13:19:03 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]:   File "/home/webtop4/.config/actions/configure-module/20config", line 282, in <module>
Nov 27 13:19:03 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]:     if user_domain["port"] != os.environ["USER_DOMAIN_PORT"]:
Nov 27 13:19:03 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]:        ~~~~~~~~~~~^^^^^^^^
Nov 27 13:19:03 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]: KeyError: 'port'
Nov 27 13:19:03 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]: task/module/webtop4/e6fe3d73-91c8-4e98-aa56-c5cfee322180: action "configure-module" status is "a
borted" (1) at step 20config
Nov 27 13:19:03 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]: Handler of module/ldapproxy1/event/user-domain-changed exited with status "completed" (0) at ste
p 10configure_module
Nov 27 13:19:04 rl1.leader.cluster0.gs.nethserver.net agent@webtop4[131920]: Handler of module/ldapproxy1/event/user-domain-changed is starting step 10configure_module
```

This can be prevented using PR https://github.com/NethServer/ns8-webtop/pull/95, but even with the fix, the user can't access WebTop.
This is the reported error:
```
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]: 2024-11-27 15:51:37 [ERROR] c.s.s.auth.directory.LdapDirectory - LdapError
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]: org.ldaptive.LdapException: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.provider.ProviderUtils.throwOperationException(ProviderUtils.java:55)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.provider.jndi.JndiConnection.processNamingException(JndiConnection.java:619)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.provider.jndi.JndiConnection.simpleBind(JndiConnection.java:261)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.provider.jndi.JndiConnection.bind(JndiConnection.java:203)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.BindOperation.invoke(BindOperation.java:28)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.BindOperation.invoke(BindOperation.java:9)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.AbstractOperation.execute(AbstractOperation.java:126)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.BindConnectionInitializer.initialize(BindConnectionInitializer.java:156)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.DefaultConnectionFactory$DefaultConnection.open(DefaultConnectionFactory.java:269)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.auth.SearchDnResolver.getConnection(SearchDnResolver.java:56)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.auth.AbstractSearchDnResolver.performLdapSearch(AbstractSearchDnResolver.java:342)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.auth.AbstractSearchDnResolver.resolve(AbstractSearchDnResolver.java:234)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.auth.Authenticator.resolveDn(Authenticator.java:233)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.auth.Authenticator.authenticate(Authenticator.java:249)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sonicle.security.auth.directory.AbstractLdapDirectory.ldapAuthenticate(AbstractLdapDirectory.java:434)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sonicle.security.auth.directory.AbstractLdapDirectory.authenticate(AbstractLdapDirectory.java:117)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sonicle.webtop.core.app.shiro.WTRealm.authenticateUser(WTRealm.java:280)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sonicle.webtop.core.app.shiro.WTRealm.doGetAuthenticationInfo(WTRealm.java:122)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:273)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:275)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.filter.authc.AuthenticatingFilter.executeLogin(AuthenticatingFilter.java:53)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.filter.authc.FormAuthenticationFilter.onAccessDenied(FormAuthenticationFilter.java:154)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sonicle.webtop.core.app.shiro.WTFormAuthFilter.onAccessDenied(WTFormAuthFilter.java:161)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.filter.AccessControlFilter.onAccessDenied(AccessControlFilter.java:133)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:223)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:198)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sonicle.webtop.core.app.shiro.filter.GZip.doFilterInternal(GZip.java:60)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sonicle.webtop.core.app.shiro.WTShiroFilter.doFilterInternal(WTShiroFilter.java:89)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1690)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at java.lang.Thread.run(Thread.java:750)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]: Caused by: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3261)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3207)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2993)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2907)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2799)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2772)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at com.sun.jndi.ldap.LdapCtx.reconnect(LdapCtx.java:2697)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at javax.naming.ldap.InitialLdapContext.reconnect(InitialLdapContext.java:193)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         at org.ldaptive.provider.jndi.JndiConnection.simpleBind(JndiConnection.java:255)
Nov 27 15:51:37 rl1.leader.cluster0.gs.nethserver.net webapp[150313]:         ... 72 common frames omitted

```

**Comment by Amygos** [comment]
Testing release `NethServer/ns8-webtop` [1.1.2-testing.3](https://github.com/NethServer/ns8-webtop/releases/tag/1.1.2-testing.3)

**Comment by stephdl** [comment]
@gsanchietti new test cases added

**Comment by gsanchietti** [comment]
All 5 test cases have been verified.

Before release, make sure #7110 is verified too.

**Comment by gsanchietti** [comment]
Back to QA.
New testing version: [1.1.2-testing.5](https://github.com/NethServer/ns8-webtop/tree/refs/tags/1.1.2-testing.5)

**Comment by stephdl** [comment]
QA set verified 

- case 1 erreur of validation of nethserver-ns8-migration

verified

- case2 migration from NS7 to NS8 with mail + webtop

verified

- case 3 direct install

verified

- case 4 change of a mail server

verified 

- case 5 change of the account provider of the mail server

verified

- case 6 upgrade from stable to testing

verified

**Comment by Amygos** [comment]
Release `NethServer/ns8-webtop`  [1.1.2](https://github.com/NethServer/ns8-webtop/releases/tag/1.1.2)

**Comment by Amygos** [comment]
Release `NethServer/ns8-webtop`  [1.1.2](https://github.com/NethServer/ns8-webtop/releases/tag/1.1.2)
